version: '3'
services:
    my-app:
    image: registry.hub.docker.com/miguelbardav/snippetwebapp:0.0.1-SNAPSHOT
    ports: 
    - "8089:8089"
    restart: always
    depends_on:
    - mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
